name: masamune_mobile
description: Library that provides mobile functions of Masamune framework. Does not work on the web.
version: 0.8.0-nullsafety.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_mobile

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  masamune: ^0.8.0-nullsafety
  firebase_model_notifier: ^0.8.0-nullsafety
  image_picker: ^0.7.0
  device_info: ^2.0.0
  package_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.5.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
