name: masamune_mobile
description: >-
  Library that provides mobile functions of Masamune framework.
  Does not work on the web.
version: 0.5.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_mobile

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Web
  http: ^0.12.1
  # Permission  
  permission_handler: ^5.0.0
  # Device
  device_info: ^0.4.1+4
  package_info: ^0.4.0+13
  image_picker: ^0.6.7+2
  # Masamune
  masamune_core: ^0.5.0
  masamune_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0

# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_localize:
#     path: ../masamune_localize/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
